### PR TITLE
KOGITO-3650: Create "Invocation" component

### PR DESCRIPTION
**Pull request by vpellegrino**
What this PR includes:
- Invocation Expression (see [there](https://vpellegrino.github.io/kie-wb-common/) in action)
- LiteralExpression, Table, and components based on table, performance enhancements: `useState` used only to trigger component tree rendering
- Table modularity improvement: `TableBody` component
- Removed unused Hooks

### CODE REVIEW

**Comment by jomarko** [comment]
### Manual check
The pop-up text for editing parameters:

#### Old
Screenshot from 2021-04-19 10-13-01


#### New
Screenshot from 2021-04-19 10-13-07

Would be possible to use 'edit parameter' text in the shown pop-up? I didn't find information if your implementation is agreed one https://issues.redhat.com/browse/KOGITO-3650

**Review by jomarko — COMMENTED** [review]
No comments to code. Thank you @vpellegrino please see the comment I had for the parameters pop-up and we can proceed.

**Comment by vpellegrino** [comment]
@jomarko I just pushed code for your point. Thanks for raising it!

**Review by jomarko — APPROVED** [review]
thank you @vpellegrino

**Review by karreiro — APPROVED** [review]
Thank you, @vpellegrino!

**Pull request merged**
